# Site settings
title: Bytecurry

description: >-
  Software Projects

theme: jekyll-theme-midnight

markdown: kramdown

#variables
links:
  github: https://github.com/bytecurry
  colliflower:
    repo: https://github.com/bytecurry/colliflower
    docs: /colliflower/overview.html

maintainer:
  url: https://github.com/tmccombs
  handle: tmccombs
